#!/bin/bash

xgettext --language=Python --keyword=_ --keyword=N_ --from-code=UTF-8 --output=menta-sources.pot \
    usr/lib/menta-sources/menta_sources.py \
    usr/lib/menta-sources/foreign_packages.py \
    usr/bin/add-apt-repository
xgettext --join-existing --from-code=UTF-8 --output=menta-sources.pot \
    usr/lib/menta-sources/menta-sources.ui \
    usr/share/applications/menta-sources.desktop
