[general]
description=Debian "Sid" (unstable)
codename=sid
# The suite name which follows this release (stable, testing, unstable)
alias=unstable
keyring=/usr/share/keyrings/debian-archive-keyring.gpg

[mirrors]
default=https://deb.debian.org/debian
security=
debug=https://deb.debian.org/debian-debug
security_debug=
mirrors=/usr/share/python-apt/templates/debian.mirrors

[components]
# Archive areas, main is always enabled
available=main contrib non-free non-free-firmware
default=main contrib non-free non-free-firmware

[suites]
# Optional suites: security updates backports proposed-updates experimental
available=experimental
default=

[keys]
keyserver=hkps://keyserver.ubuntu.com
